version: '3'

services:
  php:
    container_name: php_85
    ports: 
      - 8000:80
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  db:
    image: mysql:8.0
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
  #n8n:
  #  image: n8nio/n8n
  #  container_name: n8n
  #  ports:
  #    - "5678:5678"
  #  environment:
  #    - N8N_BASIC_AUTH_ACTIVE=true
  #    - N8N_BASIC_AUTH_USER=admin
  #    - N8N_BASIC_AUTH_PASSWORD=adminpassword
  #  volumes:
  #    - n8n_data:/home/node/.n8n
#volumes:
#  n8n_data:
